### ISSUE TITLE
Potential project for evaluation is actually archived

### ISSUE THREAD

**Issue by shriyakalakata** [joannakl/ossd#104]
Under the examples of humanitarian / social good open source projects (for evaluation), [HospitalRun](https://hospitalrun.io/) is an option. However, if you look at their [GitHub](https://github.com/HospitalRun), it shows that the projects are archived.

Suggested fix: Remove HospitalRun from the list

**Comment by laignelet16** [comment]
I suggest this open-source healthcare application: [OpenEMR](https://www.open-emr.org/). This system serves as both an Electronic Health Records (EMR) platform and a solution for managing medical practices. I also would like to fix this issue.
