### ISSUE TITLE
Individual Contribution Project Suggestion

### ISSUE THREAD

**Issue by b-chen00** [joannakl/ossd#110]
In addition to Wikipedia and OpenStreetMap, iNaturalist could be another good project to contribute to. According to google, it is a nonprofit social network of naturalists, citizen scientists, and biologists built on the concept of mapping and sharing observations of biodiversity across the globe. It is also licensed under the Creative Commons Attribution-Non-Commercial license.

If accepted, I am willing to make a pull request and add iNaturalist under Contributing to Projects on the website.

**Comment by joannakl** [comment]
This is an interesting idea. BUT, unlike Wikipedia and OpenStreetMap, the iNaturalist posts do not undergo any review. People may correct an incorrectly assigned species in the comments, but it is not the kind of review that is typical in open-source projects. 
So I would not want this is an alternative for individual contributions.
