### ISSUE TITLE
Broken link: Monetizing Open Source: Business Models That Generate Billions by Glenn Solomon

### ISSUE THREAD

**Issue by samGreer** [joannakl/ossd#111]
The link under week 11, https://cs.nyu.edu/~joannakl/ossd_s24/Monetizing%20Open%20Source:%20Business%20Models%20That%20Generate%20Billions, links to a not found page. It could be replaced with the Forbes link, https://www.forbes.com/sites/glennsolomon/2020/09/15/monetizing-open-source-business-models-that-generate-billions/?sh=673ca2ba34fd, but the link has a paywall after 4 visits

**Comment by jenna5376** [comment]
I would like to work on this!
