### ISSUE TITLE
Typos on contributions.html

### ISSUE THREAD

**Issue by kzhang01** [joannakl/ossd#12]
I've found the following typos in contributions.html:
- students' is misspelled as studnets' on slide 2
- misformatting is misspelled as miss-formatting on slide 8
- There is an extra "If you" in the fourth bullet point on slide 8
- existing is misspelled as exiting on slide 15

**Comment by ppark3** [comment]
I've also found a couple more typos in contributions.html:

- "fix" is spelled as "fixe" on slide 2
- "documentation writing" is spelled as "documnetation writing" on slide 4

**Comment by hunjunChoi** [comment]
A minor grammatical error in the same slide deck:
- "an issues" should be "an issue" on the second paragraph of slide 8.

**Comment by hunjunChoi** [comment]
Hi @joannakl, I would like to work on the issue

**Comment by joannakl** [comment]
Go ahead @hunjunChoi
