### ISSUE TITLE
Typo in week 14 assignments

### ISSUE THREAD

**Issue by benzoms** [joannakl/ossd#123]
Week 14 assignments currently read "Start workig for your project presentation."
Should say instead "Start working for your project presentation."
On [Course Website](https://cs.nyu.edu/~joannakl/ossd_s24/daily.html)

**Comment by IsaiahLevy** [comment]
I can fix this

**Comment by benzoms** [comment]
Sounds good, give it a shot

**Comment by joannakl** [comment]
closed by #133
