### ISSUE TITLE
Feature Request: Adding link to class wiki repo

### ISSUE THREAD

**Issue by JackZiyangChen** [joannakl/ossd#125]
Given that students frequently access the wiki page for various assignments and class activities, I propose that we add a link to the wiki repo somewhere on the class website for ease of access. Maybe this will increase the completion rate for the assignments too, as currently one has to navigate multiple places to find the right assignment page on the wiki.

**Comment by joannakl** [comment]
It is a private repo that is not accessible to anybody who is not registered for the class. Anyone can pin the wiki repo in the class organization on GitHub.
