### ISSUE TITLE
Incorrect due date for week 15

### ISSUE THREAD

**Issue by jenna5376** [joannakl/ossd#130]
The daily section of the course website states that the due date for week 15 assignments is "Sunday (May 4)", but Sunday is on May 5th.

<img width="1107" alt="Screenshot 2024-05-01 at 12 27 28 AM" src="https://github.com/joannakl/ossd/assets/62906996/e2b0480c-bbe9-4ab9-b6e6-dfcd80118d08">

**Comment by joannakl** [comment]
closed by #133
