### ISSUE TITLE
Dates in _includes/daily/ are incorrect

### ISSUE THREAD

**Issue by LevBernstein** [joannakl/ossd#2]
[l2.markdown](https://github.com/joannakl/ossd/blob/master/_includes/daily/l2.markdown) states that Thursday is the 26th, when it is actually the 27th; [week2.markdown](https://github.com/joannakl/ossd/blob/master/_includes/daily/week2.markdown) says that week 2 is from 9/10 - 9/16, instead of 01/30 - 02/05.

**Comment by joannakl** [comment]
@LevBernstein Thanks for pointing these out. 

The l2.markdown file is actually old and unused, so this can be just deleted. 
The best fix for week2 dates is to just remove them. The dates got copied from a different course in a different semester.
