### ISSUE TITLE
Linked video is unsupported 

### ISSUE THREAD

**Issue by hunjunChoi** [joannakl/ossd#22]
The link to "workshop video from the Indiana University of Pennsylvania (IUP) Writing Center" in the description of Lecture 2 of Week 1 is incorrectly linked. 
The correct link is https://www.iup.edu/writingcenter/writing-resources/workshop-videos/writing-a-blog.html 
However, the video on the page is no longer available, so deleting the bullet point could be a solution. 

The issues were spotted using:
- Firefox browser
- on MacOS

**Comment by rufaida99-k** [comment]
@joannakl I would like to claim this issue please! :)

**Comment by joannakl** [comment]
@rufaida99-k Go ahead. Sorry for the delay in noticing this.

**Comment by rufaida99-k** [comment]
@joannakl Thank you! Made a pull request for this issue.
