### ISSUE TITLE
Incorrect Link for "The Digital Economy Runs on Open Source. Here’s How to Protect It."

### ISSUE THREAD

**Issue by JacobLBaum** [joannakl/ossd#24]
The link in Lecture 1 section of Week 11 (4/4) for the article: "The Digital Economy Runs on Open Source. Here’s How to Protect It." is incorrect.

The link is: https://www.stern.nyu.edu/experience-stern/faculty-research/digital-economy-runs-on-open-source-how-to-protect-ithttps://hbr.org/2021/09/the-digital-economy-runs-on-open-source-heres-how-to-protect-it

It seems like an NYU Stern link was appended to the beginning of the correct URL which is at the end of the given URL.

"https://hbr.org/2021/09/the-digital-economy-runs-on-open-source-heres-how-to-protect-it" seems like it was the intended link.

I am using Chrome on Windows 10

**Comment by Ruixi-Zhang** [comment]
I would like to claim on this issue.

**Comment by joannakl** [comment]
Go ahead @Ruixi-Zhang
