### ISSUE TITLE
Typo on Week 11 Lecture 1 description

### ISSUE THREAD

**Issue by yougottawork** [joannakl/ossd#26]
![image](https://user-images.githubusercontent.com/65970555/161889185-f6e0d1d6-5a90-4be9-b7ed-82e616db7ef8.png)

Found a typo: it should be "listed in the slides".

**Comment by ian-Liaozy** [comment]
I would like to claim this issue.

**Comment by ian-Liaozy** [comment]
Hello @yougottawork , I would like to claim the issue

**Comment by joannakl** [comment]
@ian-Liaozy go ahead
