### ISSUE TITLE
Typo on Syllabus Page due to mistake in _config.yml 

### ISSUE THREAD

**Issue by aashish-khub** [joannakl/ossd#29]
The Syllabus page lists _The Cathedral and The Bazaar_ among the listed books for the course, and unfortunately states that a printed version is "available from O'Railly". The publishing house's name is spelled O'Reilly.

**Comment by aashish-khub** [comment]
Can I be assigned to fix this? I'm trying to self-assign but don't see the option to.

**Comment by joannakl** [comment]
You are not supposed to be solving your own issues.

**Comment by aashish-khub** [comment]
@joannakl Sorry about that! Will leave it open.

**Comment by cto234** [comment]
I'd like to claim this issue

**Comment by joannakl** [comment]
Go ahead @cto234

**Comment by cto234** [comment]
Looks like it has already been fixed

**Comment by joannakl** [comment]
Seems to be resolved.
