### ISSUE TITLE
Typo in textbook publisher

### ISSUE THREAD

**Issue by jinlixiao** [joannakl/ossd#34]
In the textbook section, the publisher for [The Cathedral and the Bazaar](http://www.catb.org/~esr/writings/cathedral-bazaar/) is spelled as [O'Railly](http://shop.oreilly.com/product/9781565927247.do), but it should be [O'Reilly](http://shop.oreilly.com/product/9781565927247.do).

**Comment by SivanC** [comment]
@joannakl I would like to claim this issue

**Comment by joannakl** [comment]
Go ahead @SivanC

**Comment by joannakl** [comment]
@jinlixiao Does #41 fix the issue?

**Comment by jinlixiao** [comment]
Yes it does. Thanks for working on it.
