### ISSUE TITLE
Outdated Jobs Report Link on Home Page

### ISSUE THREAD

**Issue by SivanC** [joannakl/ossd#37]
On the home page in the "Why Open Source Matters and Why Should You Care?" section, there is a link with the text "[The Linux Foundation's 2018 Open Source Jobs Report](https://www.linuxfoundation.org/publications/2018/06/open-source-jobs-report-2018/)", which currently links to the publications page for the Linux Foundation. This link should be updated to show the latest Linux Foundation jobs report, which I have linked [here](https://training.linuxfoundation.org/resources/2022-open-source-jobs-report/), and the description should be updated accordingly. The new report was published in June 2022.

**Comment by howtofly-lab** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@howtofly-lab Go for it!

**Comment by joannakl** [comment]
@SivanC Does this fix work?

**Comment by SivanC** [comment]
@joannakl Yes!
