### ISSUE TITLE
Outdated CAS Academic Calendar Link in the Website Footer

### ISSUE THREAD

**Issue by nicoleSosa** [joannakl/ossd#38]
In the footer, when you click on the link in the text ”[CAS Academic Calendar](https://www.nyu.edu/students/student-information-and-resources/registration-records-and-graduation.html),” it redirects you to an NYU page focused on helping students with Class Registration, Transcripts, Graduation. I suggest updating the link with a direct link to NYU CAS 2022-2024 Academic Calendar, which can be found [here](https://cas.nyu.edu/academic-programs/bulletin/policies/calendar.html).

**Comment by seoeunHong** [comment]
@joannakl I would like to claim this issue

**Comment by joannakl** [comment]
@nicoleSosa Does this fix the issue?

**Comment by nicoleSosa** [comment]
@joannakl yes, this fixes the issue. Thank you @seoeunHong and @joannakl.
