### ISSUE TITLE
404 Error Due to Invalid Hyperlink

### ISSUE THREAD

**Issue by shannonh800** [joannakl/ossd#43]
In the Introduction to Open Source slides (week 1, Lecture 2, slide 13), clicking on the link for Christine Peterson gets a 404 error because the underlying url--which is currently just "Christine Peterson"--seems to be directing me to a relative path that cannot be found on the server.

**Comment by jinlixiao** [comment]
@joannakl I would like to work on this issue. From the discussion in lecture I believe it should be the [wikipedia page](https://en.wikipedia.org/wiki/Christine_Peterson) right? 

Currently the issue can be seen at https://cs.nyu.edu/~joannakl/ossd_s23/slides/introduction.html#13.

**Comment by joannakl** [comment]
@jinlixiao Yes, it should be the link to the Wikipedia page.

**Comment by jinlixiao** [comment]
@shannonh800 @joannakl Does #46 fix the issue?

**Comment by shannonh800** [comment]
> @shannonh800 @joannakl Does #46 fix the issue?

Believe so!
