### ISSUE TITLE
Typo in "Contributions" Slides

### ISSUE THREAD

**Issue by shannonh800** [joannakl/ossd#48]
The title of [slide #19](https://cs.nyu.edu/~joannakl/ossd_s23/slides/contributions.html#19) in the "Contributions" slides says "Couse Website - Code of Conduct" when it should say "Course Website" instead. The html file for the slides is linked [here](https://github.com/joannakl/ossd/blob/master/slides/contributions.html).

**Comment by 2170chm** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
The title of slide 19 is intentional. That slide describes the very basic code of conduct for contributions to the course website.

**Comment by shannonh800** [comment]
Ah, I didn't mean that the title should be shortened, but that there was a typo in the first part of the title in the word "Course"
