### ISSUE TITLE
Suggestion to add this repo to course website nav bar

### ISSUE THREAD

**Issue by dinanz** [joannakl/ossd#51]
I'm unsure if this goes here in the 'issues', but I'd like to suggest adding this repo to the nav bar in the course website. The current 'GitHub' tab links to the course organisation, and since the course website is itself a demo of open source, I suggest that to conform to the ease of finding information and contributing to the website, a tab that links to this repo should be added to the nav bar.

**Comment by joannakl** [comment]
@dinanz That's a good idea.

**Comment by gracezhang89** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
Go ahead @gracezhang89
