### ISSUE TITLE
Typo in Blog/Ed/Wiki/GitHub/Wikipedia/OpenStreetMap Activity

### ISSUE THREAD

**Issue by ishana-goyal** [joannakl/ossd#52]
In the OpenStreetMap portion of the instructions, it mentions "OpenStreetMat" twice instead of "OpenStreetMap."

[Here](https://cs.nyu.edu/~joannakl/ossd_s23/activities/blog_slack_wiki_git.html) is the link to the instruction sheet and [here](https://github.com/joannakl/ossd/blob/master/activities/blog_slack_wiki_git.markdown) is the corresponding markdown sheet.

**Comment by shannonh800** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
Thanks for reporting it @ishana-goyal.
Go ahead @shannonh800
