### ISSUE TITLE
Typo in _includes/daily/week2.markdown

### ISSUE THREAD

**Issue by zhixuanevelynwu** [joannakl/ossd#6]
Under the week2 assignment section that introduces Jim Hall, it says "FeeDOS" instead of "FreeDOS".

**Comment by joannakl** [comment]
@zhixuanevelynwu Thanks for reporting this. It is definitely a bad typo!

**Comment by kzhang01** [comment]
Hi I'd like to claim this issue

**Comment by joannakl** [comment]
Go ahead @kzhang01
