### ISSUE TITLE
Week 9 invited speaker Jim Hall link broken

### ISSUE THREAD

**Issue by Jiajun-Jiao** [joannakl/ossd#61]
https://hallmentum.com/about/jimhall/ is not working. [Link to code](https://github.com/joannakl/ossd/blob/master/_includes/daily/week9.markdown)

**Comment by ishana-goyal** [comment]
Hi -- I'd like to claim this issue!

**Comment by joannakl** [comment]
@ishana-goyal How are you proposing to resolve it? 
I reached out to Jim and he suggested this link: https://personal.freedos.org/
