### ISSUE TITLE
Typo in Week 7 Assignment

### ISSUE THREAD

**Issue by 2170chm** [joannakl/ossd#62]
The week 7 assignment says that "although, you can do it this week if you do not work to do any work during the break". It is better if it says "if you do not want to do any work". The source code is [here](https://github.com/joannakl/ossd/blob/master/_includes/daily/week7.markdown).

**Comment by ishana-goyal** [comment]
I'd like to claim this issue!

**Comment by joannakl** [comment]
@ishana-goyal go for it.
