### ISSUE TITLE
Suggestion: Adding the class wiki to course website

### ISSUE THREAD

**Issue by shannonh800** [joannakl/ossd#65]
I'd like to suggest adding the class wiki to the navigation bar in the course website, similar to how there's now a tab for the class website github. We use the wiki pretty regularly as well, especially for speaker series, so I think doing this would make it more convenient for students.

**Comment by Jiajun-Jiao** [comment]
Great idea! Every time I want to access the class wiki, I need to search for its repo in GitHub. If the suggestion is acceptable, I would like to claim this issue. :)
