### ISSUE TITLE
Invalid source links in History slides

### ISSUE THREAD

**Issue by shannonh800** [joannakl/ossd#66]
In the "History" slides from last week, the links for "History of Open Source" and "The 9 most important events in open source history" take you to invalid pages (give 404 errors). These are on slide 17 and can be found in the github [here](https://github.com/joannakl/ossd/blob/master/slides/history.html) on lines 215 and 219, respectively.

**Comment by Jiajun-Jiao** [comment]
I'd like to claim this issue, the correct link to "The 9 most important events in open source history"  should be https://www.pingdom.com/blog/the-9-most-important-events-in-open-source-history/. However, for "History of Open Source" I noticed that the learning center (https://www.longsight.com/learning-center) for longsight is down, so we cannot access its original website.

**Comment by joannakl** [comment]
@Jiajun-Jiao You can work on this if you still want to. Just remove the link that is broken.
