### ISSUE TITLE
Add link to ED to course website

### ISSUE THREAD

**Issue by gracezhang89** [joannakl/ossd#69]
It might be useful to some students to have the ED section of the course website hyperlink to the actual platform. Screenshot below:

<img width="959" alt="Screenshot 2023-03-21 at 2 16 07 PM" src="https://user-images.githubusercontent.com/67801289/226704010-9d7bd473-4b70-4ec4-8df9-5816a2b8ea31.png">

**Comment by shannonh800** [comment]
I'd like to incorporate this suggestion if it's accepted!

**Comment by dinanz** [comment]
I'd like to claim this issue (if accepted).

**Comment by joannakl** [comment]
I would be open to that. But, make it a general link to Ed, not to a particular course.
@shannonh800 You can work on this if you wish.

**Comment by JackZiyangChen** [comment]
Is this issue still open and relevant for the current semester?

**Comment by JackZiyangChen** [comment]
<img width="1356" alt="Screen Shot 2024-04-14 at 12 36 49 PM" src="https://github.com/joannakl/ossd/assets/63370025/7d68b5dd-5ffa-4221-bee0-79afe240019d">
I did find that previous contributors have already added the link to the home page, but I think it might be a good idea to also add a tab at the top that links to the ED as well as it is frequently accessed by students. Attached is what I am thinking. If this is helpful I could open a PR for this with code in it.
