### ISSUE TITLE
Missing book cover in _config.yml

### ISSUE THREAD

**Issue by BradFeng02** [joannakl/ossd#7]
On the syllabus page of the course website, the book "The Linux Command Line" is missing the book cover.

**Comment by BradFeng02** [comment]
It's because there is no link in _config.yml.

I'm pretty sure book_opt_4_image on line 84 should be changed to "http://linuxcommand.org/images/lcl2_front_new.png"

If there is some reason that the image was committed before, then close this issue I guess.

**Comment by JacobLBaum** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
Go ahead @JacobLBaum

**Comment by Jiajun-Jiao** [comment]
Hi @joannakl I noticed that this issue still exist. The links to book_opt_3_image and book_opt_4_image in _config.yml are blank. Can I still claim this issue?

**Comment by joannakl** [comment]
@Jiajun-Jiao What images are you hoping to link to there?

**Comment by Jiajun-Jiao** [comment]
@joannakl For the image of **The Linux Command Line** (i.e. _book_opt_4_image_), the link could be http://linuxcommand.org/images/lcl2_front_new.png from its official website.
For the image of **Practical Open Source Software Exploration** (i.e. _book_opt_3_image_), I think the we could link to its logo https://quaid.fedorapeople.org/TOS/Practical_Open_Source_Software_Exploration/html/Common_Content/images/image_left.png, as there are no official book cover.

**Comment by joannakl** [comment]
@Jiajun-Jiao The first image is fine. For the second book, I would leave it blank. The image that you liked to is the logo for Teaching Open Source organization, http://teachingopensource.org/ , not for the book.

**Comment by Jiajun-Jiao** [comment]
@joannakl Sure, got it! Then may I make a PR for this?
