### ISSUE TITLE
Typo in Daily for Week 12 Assignments

### ISSUE THREAD

**Issue by shannonh800** [joannakl/ossd#71]
In the 1st bullet under the "Assignments" section on the right-hand side of Week 12 in the "Daily" tab, there's a typo in the name "Christopher Snider" [(it currently says "Chrispher Snider)](https://github.com/joannakl/ossd/blob/master/_includes/daily/week12.markdown)

**Comment by 2170chm** [comment]
I would like to claim this issue!

**Comment by joannakl** [comment]
@2170chm go ahead
