### ISSUE TITLE
Typo in the Contributions Slide Deck

### ISSUE THREAD

**Issue by ishana-goyal** [joannakl/ossd#72]
I noticed that on the last slide of the [Contributions deck](https://cs.nyu.edu/~joannakl/ossd_s23/slides/contributions.html#19) reads "Couse Website - Code of Conduct" instead of "Course Website - Code of Conduct". 

Here is the [source code](https://github.com/joannakl/ossd/blob/master/slides/contributions.html).

**Comment by jesings** [comment]
I would like to claim this issue!

**Comment by joannakl** [comment]
@jesings Go for it.

**Comment by jesings** [comment]
Fixed in PR #80
