### ISSUE TITLE
Typo in Week 13 Assignments List

### ISSUE THREAD

**Issue by ishana-goyal** [joannakl/ossd#73]
I noticed a small typo in the Week 13 assignments list. It currently reads "be prepared to talk briefly about the are that you found" but I believe it should read "be prepared to talk briefly about the articles that you found" or "be prepared to talk briefly about the area that you found"

Here is the [source code](https://github.com/joannakl/ossd/blob/master/_includes/daily/week13.markdown).

**Comment by joannakl** [comment]
@anpanring go ahead
