### ISSUE TITLE
Typo in Business Use in Open Source Slide Deck

### ISSUE THREAD

**Issue by ishana-goyal** [joannakl/ossd#74]
As pointed out in class, there is a missing "l" in Financial (slide 6) in the [Business Use in Open Source](https://cs.nyu.edu/~joannakl/ossd_s23/slides/business_use_open_source.html#6) slide deck. 

Here is the [source code](https://github.com/joannakl/ossd/blob/master/slides/business_use_open_source.html).

**Comment by gracezhang89** [comment]
I would like to claim this issue!

**Comment by joannakl** [comment]
@gracezhang89 go ahead
