### ISSUE TITLE
Invalid link in Business Models slides

### ISSUE THREAD

**Issue by shannonh800** [joannakl/ossd#78]
The link titled "The Linux Foundation's 2021 Open Source Jobs Report" gives a 404 error when clicked on. The link is located on slide 2 of the "Business Models" slides, which can be found [here](https://github.com/joannakl/ossd/blob/master/slides/business_models.html)

**Comment by ishana-goyal** [comment]
I'd like to claim this issue! 

There are two possible links that I think would work here:
(1) the actual 2021 report, which can be found [here](https://www.linuxfoundation.org/research/the-2021-open-source-jobs-report). 
(2) or the [2018 report](https://training.linuxfoundation.org/wp-content/uploads/2022/05/OpenSourceJobsReport_2018_FINAL.pdf), which is cited in the subtext of this slide (re: 'is a report on jobs in the open source world in 2018'). 

If the first link is more appropriate, I'd also like to change the subtext to read 'is a report on jobs in the open source world in 2021'. 

Please let me know what you think! @joannakl

**Comment by joannakl** [comment]
It's been a long time and I am not sure if this is still relevant. Closing. Maybe future semester students can pick it up.
