### ISSUE TITLE
Suggestion: Update the Week Begin Dates on the Website Daily Page

### ISSUE THREAD

**Issue by ishana-goyal** [joannakl/ossd#82]
I noticed on the Daily tab of the course website that each of the week begin dates fall on the Monday of the week, except for two weeks -- Week 11 and Week 12, whose dates fall on the Tuesday of that week (4/4 and 4/11, respectively). For consistency, I recommend we change those to 4/3 and 4/10, respectively. 

Please ignore this suggestion if this was done intentionally to account for April holidays (though the NYU academic calendar does not recognize those Monday's as holidays).

**Comment by shannonh800** [comment]
I'd like to work on this if accepted!

**Comment by joannakl** [comment]
No longer applicable.
