### ISSUE TITLE
Invalid link in Daily/week1.markdown

### ISSUE THREAD

**Issue by wwwld1** [joannakl/ossd#84]
In [week1](https://github.com/joannakl/ossd/blob/master/_includes/daily/week1.markdown?plain=1#L29), the video [Open Source Basics](https://youtu.be/Tyd0FO0tko8) by Intel Software is private and unavailable.

**Comment by SamFrank234** [comment]
I'd like to suggest [this video](https://www.youtube.com/watch?v=PVD1LNDxOnc) (Open Source Explained by IBM) as a potential replacement, and would be happy to make the change to the site if I am assigned to this issue.
