### ISSUE TITLE
Git Intro Activity Demo Improvement

### ISSUE THREAD

**Issue by SamFrank234** [joannakl/ossd#86]
Summary:
There was some confusion during the demo today when it came to pulling divergent branches. I think it can be easily fixed in the future with a simple addition.

Bug:
When pulling the upstream main (see [slides](https://cs.nyu.edu/~joannakl/ossd_s24/slides/git_intro_activity.html#16)), some students received an error message along the lines of `fatal: Need to specify how to reconcile divergent branches.`

Reproduce:
Check if you have specified a reconciliation method for pulls via `git config -get pull.rebase` and `git config -get pull.ff`. If so, you can delete these from your config (`git config --unset [name]`) and try pulling again. If there are divergent branches, you should get the error message.

Proposed Solution:
Instead of `git pull upstream main`, have students run `git pull upstream main --no-rebase`. This will disregard any config variables which may or may not be set, and ensure that when they pull divergent branches, git attempts to merge the two histories.

**Comment by joannakl** [comment]
I like that suggestion.

**Comment by joannakl** [comment]
closed by #133
