### ISSUE TITLE
Recommend Improving CAS Calendar Link 

### ISSUE THREAD

**Issue by IsaiahLevy** [joannakl/ossd#94]
The current CAS calendar link is fine but by default shows the 2022 schedule. I recommend a refined calendar link with a more narrow window reflective of our course time line. An example is [CAS Calendar](https://www.nyu.edu/students/student-information-and-resources/registration-records-and-graduation/academic-calendar.html?startDate=2024-01-01&endDate=2024-06-19) which uses the filter feature (in the link) to show the 2024 calendar from 01/01 2024 to 06/19 2024.

**Comment by joannakl** [comment]
I do not want the link to be that specific as it appears in the footer of every course every semester. It is up to CAS to have the current years/semesters listed there. Universities often leave older calendars up for reference.
