### ISSUE TITLE
Suggestion: Make book images clickable 

### ISSUE THREAD

**Issue by andrewhuanggg** [joannakl/ossd#96]
In the home page of the course website, under the 'Course Materials' heading, there is a list of books and their respective images and titles. Currently, you can only get to the books by clicking on the titles, and clicking on the images does nothing. I think that the images should also be clickable, and redirect the users to the URL pertaining to the book they are trying to read.

**Comment by joannakl** [comment]
@andrewhuanggg Thanks for the suggestion.
A long time ago, they used to be. But for some reason (that I no longer remember) this changed. I think it may have been too much of a headache to update and track links and images as they change.
